name: Formal & Static Verification
nonces' = nonces


Next == Encrypt \/ Rotate


Spec == Init /\ [][Next]_<<seq, keyVersion, nonces>>


NonceCardinality == Cardinality(nonces) = seq


KeyVersionNonDecr == keyVersion >= 0


=============================================================================
TLA
fi


# Minimal Apalache configuration (bound MaxNonce for bounded model checking)
if [ ! -f formal/chachacrypt.cfg ]; then
cat > formal/chachacrypt.cfg <<'CFG'
# Apalache configuration for chachacrypt.tla
Init: chachacrypt!Init
Next: chachacrypt!Next
Inv: chachacrypt!NonceCardinality
Inv: chachacrypt!KeyVersionNonDecr
--bound MaxNonce 5
CFG
fi


- name: Run Apalache model checker (Docker)
# We try pulling a community Apalache image; make this step non-blocking.
continue-on-error: true
run: |
set -euo pipefail
echo "Running Apalache model checker (docker)..."
# mount repo root as /workdir inside container
docker run --rm -v "$PWD":/workdir informalsystems/apalache:latest apalache-mc check /workdir/formal/chachacrypt.tla 2>&1 | tee apalache.log || true


- name: Upload Apalache log
if: always()
uses: actions/upload-artifact@v4
with:
name: apalache-log
path: apalache.log


optional-proverif:
name: Optional ProVerif run (if `formal/proverif.pv` present)
runs-on: ubuntu-latest
needs: static-analysis
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Run ProVerif if model is present
continue-on-error: true
run: |
set -euo pipefail
if [ -f formal/proverif.pv ]; then
echo "proverif input found: running ProVerif (requires docker/proverif)."
# Try Docker ProVerif image if available. This is best-effort.
docker run --rm -v "$PWD":/data frart/proverif proverif /data/formal/proverif.pv 2>&1 | tee proverif.log || true
echo "Uploaded proverif.log"
else
echo "No formal/proverif.pv found; skipping ProVerif step."
fi
- name: Upload ProVerif log
if: always()
uses: actions/upload-artifact@v4
with:
name: proverif-log
path: proverif.log
if-no-files-found: ignore
