# .goreleaser.yml
version: 2
dist: dist

# Project name (used for archive names, homebrew formula, etc)
project_name: "{{ .RepoName }}"

before:
  hooks:
    - go mod download

builds:
  - id: main
    main: .                      # change to ./cmd/mycli if needed
    binary: '{{ .ProjectName }}'
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # build GOAMD64 variants when GOARCH=amd64
    goamd64:
      - v2
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - '-s -w'

archives:
  # raw binaries (no wrapping dir)
  - id: raw-binaries
    format: binary
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}{{ .ArtifactExt }}'
    wrap_in_directory: false

  # packaged archives (tar.gz on unix, zip on windows)
  - id: packaged
    format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true

checksum:
  # combined checksum file uploaded by GoReleaser (SHA256 per artifact)
  name_template: '{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS'
  algorithm: sha256

# UPX is an array of UPX rules (v2 schema). Define one rule that applies to all builds.
upx:
  - enabled: true
    # compress can be 1..9 or 'best'
    compress: '9'
    # try LZMA (optional)
    lzma: false
    # brute (optional, slower)
    brute: false
    # example filters (optional) - remove or adapt if you want to restrict which builds get UPX'd
    # ids: [main]
    # goos: [linux]
    # goarch: [amd64, arm64]

release:
  # release name (templates allowed). Put name_template at top-level release, not inside release.github
  name_template: '{{ .Tag }}'
  github:
    # optionally specify owner/name if you want to force a different repo for the release.
    # owner: your-org
    # name: your-repo
    # leaving unset makes GoReleaser infer from git remote
    # owner: user
    # name: repo

    # NOTE: 'name_template' does NOT belong under github; putting it there triggers "field name_template not found in type config.Repo"
