# .goreleaser.yml (v2-compatible)
version: 2
dist: dist

# Don't hardcode a template here. Let goreleaser infer the project name
# from the git remote (recommended). That makes .ProjectName available
# to templates and guarantees consistent artifact filenames.
# project_name: my-project   # optional override (string). DON'T use literal templates here.

before:
  hooks:
    - go mod download

builds:
  - id: main
    main: .                      # change to ./cmd/mycli if needed
    # Use the project name as the binary name so artifacts are named
    # after the repository/project (not 'main').
    binary: '{{ .ProjectName }}'
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - '-s -w'

archives:
  - id: raw-binaries
    formats:
      - binary
    # name_template uses .ProjectName (inferred) + tag + os/arch
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}{{ .ArtifactExt }}'
    wrap_in_directory: false

  - id: packaged
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS'
  algorithm: sha256

# UPX array (v2)
upx:
  - enabled: true
    compress: '9'
    lzma: false
    brute: false

release:
  name_template: '{{ .Tag }}'
  github:
    # optional: override owner/name if you need to publish to a repo different from origin
    # owner: your-org
    # name: your-repo
