# .goreleaser.yml (v2-compatible)
version: 2
dist: dist

project_name: "{{ .RepoName }}"

before:
  hooks:
    - go mod download

builds:
  - id: main
    main: .                      # change to ./cmd/mycli if needed
    binary: '{{ .ProjectName }}'
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - '-s -w'

archives:
  - id: raw-binaries
    formats:
      - binary
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}{{ .ArtifactExt }}'
    wrap_in_directory: false

  - id: packaged
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Amd64 }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS'
  algorithm: sha256

# UPX is an array in v2 ─ provide a single rule applicable to your builds
upx:
  - enabled: true
    compress: '9'
    lzma: false
    brute: false

release:
  # templates allowed (default was '{{ .Tag }}'); keep explicit
  name_template: '{{ .Tag }}'
  github:
    # owner/name optional — GoReleaser infers from git remote unless you need to override
    # owner: your-org
    # name: repo-name
