name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.25.x
      - name: Cache Go modules
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install staticcheck (optional)
        run: |
          if ! command -v staticcheck > /dev/null; then
            go install honnef.co/go/tools/cmd/staticcheck@latest || true
          fi
      - name: Install golangci-lint (optional)
        run: |
          if ! command -v golangci-lint > /dev/null; then
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3 || true
          fi
      - name: Tidy modules
        run: go mod tidy
      - name: Run gofmt check
        run: test -z "$(gofmt -l .)"
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Staticcheck (if available)
        run: staticcheck ./... || true
      - name: Unit tests
        run: go test -v ./...
