name:+==%8)(8&5)5=5%((=='':%+-=^[<]©[™]¦]¦¶]§]<]<[^




name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.25.x]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify go.mod is tidy
        run: go mod tidy

      - name: Run gofmt (auto-fix)
        run: gofmt -w .

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        if: matrix.os == 'ubuntu-latest' # only run once
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2025.1.1
          staticcheck ./...

      - name: golangci-lint
        if: matrix.os == 'ubuntu-latest' # only run once
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v2.4.0
          golangci-lint run ./...

      - name: Unit tests (with race detector)
        run: go test -v -race ./...
