name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
            go-version: 1.23

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Run mod init
        run: go mod init chachacrypt -v ./...
  
      - name: Run tidy init
        run: go mod tidy -v ./...

      - name: Build
        run: go build -v ./...
