name: Go Automated Updates

on:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  go_language_update:
    runs-on: ubuntu-latest
    name: "Automate Go Language Version Update"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Go environment"
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: "Update go.mod to latest Go version"
        run: |
          go mod edit -go=${{ steps.setup-go.outputs.go-version }}

      - name: "Run AI-powered refactoring for Go version compatibility"
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          AI_MODEL: "deepseek/deepseek-r1:free"
        run: |
          chmod +x.github/scripts/ai_refactor.sh && ./.github/scripts/ai_refactor.sh go-version https://openrouter.ai/api/v1/chat/completions

      - name: "Validate changes and run tests"
        run: |
          go mod tidy
          go mod verify
          go test./...

      - name: "Create Pull Request for Go version update"
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore(go): update Go language version to ${{ steps.setup-go.outputs.go-version }}"
          title: "chore(go): Update Go Language Version to ${{ steps.setup-go.outputs.go-version }}"
          body: |
            ## Automated Go Language Update
            This PR automatically updates the project to the latest stable Go language version (**${{ steps.setup-go.outputs.go-version }}**).

            - **Rationale:** This ensures the project remains up-to-date with the latest performance enhancements and security patches.
            - **Changes:** The `go.mod` file has been updated, and the AI-powered refactoring engine has modified code to ensure compatibility.
            
            This is an automated PR. Please review and merge if all checks pass.
          branch: "automated-go-version-update"

  go_dependency_update:
    needs: go_language_update
    runs-on: ubuntu-latest
    name: "Automate Dependency Updates and Refactoring"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Go environment"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: "Update all dependencies"
        run: |
          go get -u all
          go mod tidy

      - name: "Run AI-powered refactoring for dependency compatibility"
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          AI_MODEL: "deepseek/deepseek-r1:free"
        run: |
          chmod +x.github/scripts/ai_refactor.sh && ./.github/scripts/ai_refactor.sh dependencies https://openrouter.ai/api/v1/chat/completions

      - name: "Validate changes and run tests"
        run: |
          go mod tidy
          go mod verify
          go test./...

      - name: "Create Pull Request for dependency updates"
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore(deps): automated dependency update and refactoring"
          title: "chore(deps): Automated Dependency Update and Refactoring"
          body: |
            ## Automated Dependency Update
            This PR automatically updates all project dependencies to their latest versions and attempts to resolve any breaking changes using an AI-powered refactoring engine.

            - **Rationale:** This ensures the project uses the latest features, security patches, and performance improvements from its dependencies.
            - **Changes:** The `go.mod` and `go.sum` files have been updated, and source code may have been modified to maintain compatibility.
            
            This is an automated PR. Please review and merge if all checks pass.
          branch: "automated-dependency-update"
