name: CI_Gemini

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  go_language_update:
    runs-on: ubuntu-latest
    name: "Automate Go Language & Dependency Update"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Update go.mod to latest resolved Go version
        run: |
          GO_VER="${{ steps.setup-go.outputs.go-version || 'stable' }}"
          echo "Updating go.mod to go ${GO_VER}"
          go mod edit -go=${GO_VER}

      - name: Run go mod tidy
        run: |
          go mod tidy

      - name: Run AI-powered refactoring for dependency compatibility
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          AI_MODEL: "deepseek/deepseek-r1:free"
        run: |
          chmod +x ./.github/scripts/ai_refactor.sh
          ./.github/scripts/ai_refactor.sh dependencies https://openrouter.ai/api/v1/chat/completions

      - name: Validate changes and run tests
        run: |
          go mod tidy
          go mod verify || true
          go vet ./... || true
          go test ./...

      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for dependency updates
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: automated-dependency-update
          title: "chore(deps): Automated Dependency Update and Refactoring"
          commit-message: "chore(deps): automated dependency update and refactoring"
          body: |
            ## Automated Dependency Update
            This PR automatically updates project dependencies and applies compatibility refactors (AI-assisted) where necessary.

            - **Rationale:** keep dependencies up-to-date to pick up bug fixes, security patches, and performance improvements.
            - **Changes:** `go.mod` and `go.sum` may have been updated; source code may have been modified to maintain compatibility.

            This is an automated PR. Please review and merge if all checks pass.
          token: ${{ secrets.G H_TOKEN }}
