# .github/workflows/CI_Gemini.yml
name: CI_Gemini

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  checks: write
  pull-requests: write

concurrency:
  group: ci-gemini
  cancel-in-progress: false

jobs:
  update-and-refactor:
    name: Automated dependency & toolchain update with AI refactor
    runs-on: ubuntu-latest
    env:
      AI_MODEL: "tngtech/deepseek-r1t2-chimera:free"
      API_URL: "https://openrouter.ai/api/v1/chat/completions"
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git
        run: |
          git config user.name "ci-gemini-bot"
          git config user.email "ci-gemini-bot@users.noreply.github.com"

      - name: Set up Go (stable)
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Cache Go modules
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install essentials and build tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq curl git build-essential ca-certificates

      - name: Install gitleaks (built with runner Go) and golangci-lint (built with runner Go)
        run: |
          set -euo pipefail
          # Ensure module-aware go install and ensure bin directory exists
          GO_BIN="$(go env GOBIN 2>/dev/null || true)"
          if [ -z "${GO_BIN}" ]; then
            GO_BIN="$(go env GOPATH 2>/dev/null)/bin"
          fi
          mkdir -p "${GO_BIN}"
          # Install gitleaks v8.28.0 (built from source by go install)
          GOFLAGS="" GOBIN="${GO_BIN}" go install github.com/zricethezav/gitleaks/v8@v8.28.0
          # Install golangci-lint v2.4.0 (build from source)
          GOFLAGS="" GOBIN="${GO_BIN}" go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.4.0
          # Ensure binaries are on PATH for subsequent steps
          sudo mv "${GO_BIN}/gitleaks" /usr/local/bin/gitleaks || true
          sudo mv "${GO_BIN}/golangci-lint" /usr/local/bin/golangci-lint || true
          if ! command -v gitleaks >/dev/null 2>&1; then
            echo "gitleaks installation failed" >&2
            exit 1
          fi
          if ! command -v golangci-lint >/dev/null 2>&1; then
            echo "golangci-lint installation failed" >&2
            exit 1
          fi
          gitleaks version || true
          golangci-lint --version || true

      - name: Ensure script is executable
        run: chmod +x ./.github/scripts/ai_refactor.sh

      - name: Run automated updates + AI refactor
        id: run_refactor
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail
          ./.github/scripts/ai_refactor.sh dependencies "${{ env.API_URL }}" "${{ env.AI_MODEL }}"

      - name: Upload artifacts (AI request/response, patch, logs)
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ci-gemini-artifacts
          path: |
            ai-request.json
            ai-response.json
            ai.patch
            tests.log
            linter.log
            gitleaks.log

      - name: Final status
        if: always()
        run: |
          echo "CI_Gemini finished. Check artifacts for AI request/response and logs."
