name: signing_files

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  signing_files:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # This step ensures that your project is available in the workflow environment.
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # This step uses 'gh-action-sigstore-python' to sign the file designated in the inputs field.
      - uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: to_be_signed.txt
