# workflow name
name: go-cross-build

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Specify the Go version

      - name: Download Go modules
        run: go mod download  # Ensure that all modules are downloaded, including the missing one

      - name: Tidy Go modules
        run: go mod tidy  # Clean up go.mod and go.sum, ensuring all required dependencies are listed

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        with:
            platforms: 'linux/amd64'
            package: 'chachacrypt'
            name: 'chachacrypt'
            compress: 'true'
            dest: 'dist'
