# workflow name
name: go-cross-build

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'  # Specify Go version to use

      - name: Download Go modules
        run: |
          go mod download golang.org/x/crypto@v0.28.0
          go mod download golang.org/x/net@v0.21.0
          go mod download  # Download all remaining dependencies

      - name: Tidy Go modules
        run: go mod tidy  # Clean up go.mod and go.sum

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        with:
          platforms: 'linux/amd64'
          package: 'chachacrypt'
          name: 'chachacrypt'
          compress: 'true'
          dest: 'dis'
