name: Update Go Version in go.mod Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs weekly
  workflow_dispatch: {}  # Allow manual triggering

jobs:
  update-go-mod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Confirm Go installation
        run: |
          echo "Using the system-installed Go: $(go version)"

      - name: Fetch the latest Go full version
        id: go-info
        run: |
          # Get the installed Go version, e.g. "go1.24.2"
          full_version=$(go version | awk '{print $3}' | sed 's/^go//')
          echo "Latest Go full version: $full_version"
          # Export the full version (e.g. "1.24.2") to subsequent steps
          echo "latest_go_full=$full_version" >> $GITHUB_ENV

      - name: Find and update go.mod files
        id: update
        run: |
          changes_made=false
          echo "Latest Go version (full): $latest_go_full"
          
          # Locate all go.mod files in the repository (including subfolders)
          for file in $(find . -name "go.mod"); do
            echo "Processing $file"
            # Extract the current go directive; e.g., "1.24", "1.24.1", etc.
            current_go=$(grep '^go ' "$file" | awk '{print $2}')
            if [ -z "$current_go" ]; then
              echo "No 'go' directive found in $file, skipping."
              continue
            fi
            echo "Current Go version in $file: $current_go"
            
            # Compare the versions using sort -V so that e.g. 1.24.2 > 1.24.1 and 1.24.2 > 1.24
            if [ "$(printf '%s\n' "$latest_go_full" "$current_go" | sort -V | tail -n1)" != "$current_go" ]; then
              echo "Updating $file: setting Go version to $latest_go_full"
              sed -i "s/^go .*/go $latest_go_full/" "$file"
              changes_made=true
            fi
          done

          if [ "$changes_made" = true ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git checkout -B update-go-version
            git commit -am "Update go.mod files: set Go version to $latest_go_full"
            echo "changes_made=true" >> $GITHUB_ENV
          else
            echo "changes_made=false" >> $GITHUB_ENV
            echo "No updates needed for any go.mod files"
          fi

      - name: Push changes if any were made
        if: env.changes_made == 'true'
        run: |
          git push origin update-go-version --force

      - name: Create pull request if needed
        if: env.changes_made == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          repo=${GITHUB_REPOSITORY}
          api_url="https://api.github.com/repos/${repo}/pulls"
          title="Update go.mod files: set Go version to $latest_go_full"
          body="This pull request updates all go.mod files in the repository by setting the Go version in the 'go' directive to $latest_go_full."
          head="update-go-version"
          base="$DEFAULT_BRANCH"
          
          # Check if a pull request for the branch already exists
          existing_pr=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${repo}/pulls?head=${repo}:$head")
          if echo "$existing_pr" | grep -q "\"number\":"; then
            echo "A pull request for branch $head already exists."
          else
            # Create a new pull request
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -X POST "$api_url" \
              -d "{\"title\":\"$title\",\"head\":\"$head\",\"base\":\"$base\",\"body\":\"$body\"}"
            echo "Pull request created."
          fi
