name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  golangci:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Install golangci-lint (binary)
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.5.0
          install-mode: binary
        continue-on-error: true

      - name: Run golangci-lint (linux)
        if: matrix.os == 'ubuntu-latest'
        id: run-golangci-linux
        continue-on-error: true
        shell: bash
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          set -euo pipefail || true
          mkdir -p artifacts
          cd "$GITHUB_WORKSPACE"
          # Run linter and capture both stdout and stderr to files; do not let the step fail the job
          golangci-lint run --out-format json ./... > artifacts/golangci.json 2> artifacts/golangci.stderr || true
          golangci-lint --version > artifacts/golangci.version 2>&1 || true
          echo "ran_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > artifacts/runinfo.txt || true

      - name: Run golangci-lint (windows)
        if: matrix.os == 'windows-latest'
        id: run-golangci-windows
        continue-on-error: true
        shell: pwsh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          New-Item -ItemType Directory -Path artifacts -Force | Out-Null
          Set-Location -Path $Env:GITHUB_WORKSPACE
          # Run linter and capture outputs; do not fail the step
          & golangci-lint run --out-format json ./... > artifacts/golangci.json 2> artifacts/golangci.stderr || Write-Output "golangci-lint run returned non-zero"
          & golangci-lint --version > artifacts/golangci.version 2>&1 || Write-Output "golangci-lint --version failed"
          (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ") | Out-File -FilePath artifacts/runinfo.txt -Encoding ascii

      - name: Upload golangci-lint artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: golangci-lint-results-${{ matrix.os }}
          path: artifacts/
          retention-days: 7
