name: Lint
on:
  pull_request:
    branches: [ main ]
env:
  # environment variables shared between build steps
  # do not include sensitive credentials and tokens here, instead pass them
  # directly to tools that need them to limit the blast radius in case one of them
  # becomes compromised and leaks credentials to external sites.
  # required by Makefile
  UNIX_SHELL_ON_WINDOWS: true
  # set (to any value other than false) to trigger random unicode filenames testing (logs may be difficult to read)
  ENABLE_UNICODE_FILENAMES: ${{ secrets.ENABLE_UNICODE_FILENAMES }}
  # set (to any value other than false) to trigger very long filenames testing
  ENABLE_LONG_FILENAMES: ${{ secrets.ENABLE_LONG_FILENAMES }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version-file: 'go.mod'
    - id: govulncheck
      uses: golang/govulncheck-action@v1.0.4
      with:
        cache: false
        go-version-input: '1.25.1'
        # An explicit Go version is needed for govulncheck-action since internally
        # it uses an outdated setup-go@v5.0 action that does not respect the 'toolchain'
        # directive in the 'go.mod' file.
        #go-version-file: 'go.mod'
        repo-checkout: false
    - name: Lint
      run: make lint
    - name: Check Locks
      run: make check-locks
    - name: Prettier
      run: make check-prettier
