name: staticcheck-action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest"]
        go:  ["1.25.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 3
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.4.0
      with:
        version: "latest"
        install-go: false
        cache-key: ${{ matrix.go }}
        working-directory: ${{ matrix.dir }}
        GOTOOLCHAIN: v1.25.1
