name: staticcheck-action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  staticcheck-action:
    name: "staticcheck-action"
    strategy:
      fail-fast: false
      matrix:
        go: ["stable"]
        os: ["windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 3
    - uses: actions/setup-go@v6.0.0
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.4.0
      with:
        version: "latest"
        install-go: false
        working-directory: ${{ matrix.dir }}
