name: Upgrade Go

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  

jobs:
  upgrade-go:
    runs-on: ubuntu-latest
    permissions: # Only required if using default `secrets.GITHUB_TOKEN`
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@main
      - uses: StefMa/Upgrade-Go-Action@main
        with:
          base-branch: 'master'
          gh-token: ${{ secrets.CUSTOM_TOKEN }}
