name: Upgrade Go

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  

jobs:
  upgrade-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: StefMa/Upgrade-Go-Action@main
        with:
          base-branch: 'master'
